[package]
name = "sirara_core"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.18"
bigdecimal = "0.4"
uuid = { version = "1", features = ["serde", "v4"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres", "bigdecimal", "macros",  "uuid", "bigdecimal", "chrono", "json",] }
config = "0.14"
serde = { version = "1", features = ["derive"] }
dotenvy = "0.15"
anyhow = "1"
humantime = "2"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json", "gzip", "brotli", "deflate", "rustls-tls"] }
num-traits = "0.2.19"
async-trait = "0.1.89"
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0.149"
bs58 = "0.5"
hex = "0.4"
sha2 = "0.10"
k256 = { version = "0.13", features = ["ecdsa"] }
tiny-keccak = { version = "2", features = ["keccak"] }
sha3 = "0.10"
base64 = "0.22"
solana-client = "1.18"
solana-sdk = "1.18"
spl-token = "4"
spl-associated-token-account = "2"

[dev-dependencies]

serial_test = "3"
